// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: levelone_quote.proto

package kaqt.providers.protobuf;

public final class LeveloneQuote {
  private LeveloneQuote() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LevelOneQuoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kaqt.providers.protobuf.LevelOneQuote)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 instrument_id = 1;</code>
     */
    boolean hasInstrumentId();
    /**
     * <code>required int32 instrument_id = 1;</code>
     */
    int getInstrumentId();

    /**
     * <code>required double bid = 2;</code>
     */
    boolean hasBid();
    /**
     * <code>required double bid = 2;</code>
     */
    double getBid();

    /**
     * <code>required double ask = 3;</code>
     */
    boolean hasAsk();
    /**
     * <code>required double ask = 3;</code>
     */
    double getAsk();

    /**
     * <code>required double last = 4;</code>
     */
    boolean hasLast();
    /**
     * <code>required double last = 4;</code>
     */
    double getLast();

    /**
     * <code>required int32 bid_qty = 5;</code>
     */
    boolean hasBidQty();
    /**
     * <code>required int32 bid_qty = 5;</code>
     */
    int getBidQty();

    /**
     * <code>required int32 ask_qty = 6;</code>
     */
    boolean hasAskQty();
    /**
     * <code>required int32 ask_qty = 6;</code>
     */
    int getAskQty();

    /**
     * <code>required int32 last_qty = 7;</code>
     */
    boolean hasLastQty();
    /**
     * <code>required int32 last_qty = 7;</code>
     */
    int getLastQty();

    /**
     * <code>required int64 posix_time = 8;</code>
     */
    boolean hasPosixTime();
    /**
     * <code>required int64 posix_time = 8;</code>
     */
    long getPosixTime();
  }
  /**
   * Protobuf type {@code kaqt.providers.protobuf.LevelOneQuote}
   */
  public static final class LevelOneQuote extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:kaqt.providers.protobuf.LevelOneQuote)
      LevelOneQuoteOrBuilder {
    // Use LevelOneQuote.newBuilder() to construct.
    private LevelOneQuote(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LevelOneQuote(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LevelOneQuote defaultInstance;
    public static LevelOneQuote getDefaultInstance() {
      return defaultInstance;
    }

    public LevelOneQuote getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LevelOneQuote(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              instrumentId_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              bid_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              ask_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              last_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              bidQty_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              askQty_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              lastQty_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              posixTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kaqt.providers.protobuf.LeveloneQuote.internal_static_kaqt_providers_protobuf_LevelOneQuote_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kaqt.providers.protobuf.LeveloneQuote.internal_static_kaqt_providers_protobuf_LevelOneQuote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote.class, kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote.Builder.class);
    }

    public static com.google.protobuf.Parser<LevelOneQuote> PARSER =
        new com.google.protobuf.AbstractParser<LevelOneQuote>() {
      public LevelOneQuote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LevelOneQuote(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LevelOneQuote> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INSTRUMENT_ID_FIELD_NUMBER = 1;
    private int instrumentId_;
    /**
     * <code>required int32 instrument_id = 1;</code>
     */
    public boolean hasInstrumentId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 instrument_id = 1;</code>
     */
    public int getInstrumentId() {
      return instrumentId_;
    }

    public static final int BID_FIELD_NUMBER = 2;
    private double bid_;
    /**
     * <code>required double bid = 2;</code>
     */
    public boolean hasBid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double bid = 2;</code>
     */
    public double getBid() {
      return bid_;
    }

    public static final int ASK_FIELD_NUMBER = 3;
    private double ask_;
    /**
     * <code>required double ask = 3;</code>
     */
    public boolean hasAsk() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double ask = 3;</code>
     */
    public double getAsk() {
      return ask_;
    }

    public static final int LAST_FIELD_NUMBER = 4;
    private double last_;
    /**
     * <code>required double last = 4;</code>
     */
    public boolean hasLast() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double last = 4;</code>
     */
    public double getLast() {
      return last_;
    }

    public static final int BID_QTY_FIELD_NUMBER = 5;
    private int bidQty_;
    /**
     * <code>required int32 bid_qty = 5;</code>
     */
    public boolean hasBidQty() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 bid_qty = 5;</code>
     */
    public int getBidQty() {
      return bidQty_;
    }

    public static final int ASK_QTY_FIELD_NUMBER = 6;
    private int askQty_;
    /**
     * <code>required int32 ask_qty = 6;</code>
     */
    public boolean hasAskQty() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 ask_qty = 6;</code>
     */
    public int getAskQty() {
      return askQty_;
    }

    public static final int LAST_QTY_FIELD_NUMBER = 7;
    private int lastQty_;
    /**
     * <code>required int32 last_qty = 7;</code>
     */
    public boolean hasLastQty() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 last_qty = 7;</code>
     */
    public int getLastQty() {
      return lastQty_;
    }

    public static final int POSIX_TIME_FIELD_NUMBER = 8;
    private long posixTime_;
    /**
     * <code>required int64 posix_time = 8;</code>
     */
    public boolean hasPosixTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int64 posix_time = 8;</code>
     */
    public long getPosixTime() {
      return posixTime_;
    }

    private void initFields() {
      instrumentId_ = 0;
      bid_ = 0D;
      ask_ = 0D;
      last_ = 0D;
      bidQty_ = 0;
      askQty_ = 0;
      lastQty_ = 0;
      posixTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInstrumentId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAsk()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLast()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBidQty()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAskQty()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastQty()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosixTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, instrumentId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, bid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, ask_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, last_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, bidQty_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, askQty_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, lastQty_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, posixTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, instrumentId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, bid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, ask_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, last_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, bidQty_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, askQty_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, lastQty_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, posixTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kaqt.providers.protobuf.LevelOneQuote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kaqt.providers.protobuf.LevelOneQuote)
        kaqt.providers.protobuf.LeveloneQuote.LevelOneQuoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kaqt.providers.protobuf.LeveloneQuote.internal_static_kaqt_providers_protobuf_LevelOneQuote_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kaqt.providers.protobuf.LeveloneQuote.internal_static_kaqt_providers_protobuf_LevelOneQuote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote.class, kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote.Builder.class);
      }

      // Construct using kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        instrumentId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        bid_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        ask_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        last_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        bidQty_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        askQty_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        lastQty_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        posixTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kaqt.providers.protobuf.LeveloneQuote.internal_static_kaqt_providers_protobuf_LevelOneQuote_descriptor;
      }

      public kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote getDefaultInstanceForType() {
        return kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote.getDefaultInstance();
      }

      public kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote build() {
        kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote buildPartial() {
        kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote result = new kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.instrumentId_ = instrumentId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bid_ = bid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ask_ = ask_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.last_ = last_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.bidQty_ = bidQty_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.askQty_ = askQty_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.lastQty_ = lastQty_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.posixTime_ = posixTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote) {
          return mergeFrom((kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote other) {
        if (other == kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote.getDefaultInstance()) return this;
        if (other.hasInstrumentId()) {
          setInstrumentId(other.getInstrumentId());
        }
        if (other.hasBid()) {
          setBid(other.getBid());
        }
        if (other.hasAsk()) {
          setAsk(other.getAsk());
        }
        if (other.hasLast()) {
          setLast(other.getLast());
        }
        if (other.hasBidQty()) {
          setBidQty(other.getBidQty());
        }
        if (other.hasAskQty()) {
          setAskQty(other.getAskQty());
        }
        if (other.hasLastQty()) {
          setLastQty(other.getLastQty());
        }
        if (other.hasPosixTime()) {
          setPosixTime(other.getPosixTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInstrumentId()) {
          
          return false;
        }
        if (!hasBid()) {
          
          return false;
        }
        if (!hasAsk()) {
          
          return false;
        }
        if (!hasLast()) {
          
          return false;
        }
        if (!hasBidQty()) {
          
          return false;
        }
        if (!hasAskQty()) {
          
          return false;
        }
        if (!hasLastQty()) {
          
          return false;
        }
        if (!hasPosixTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kaqt.providers.protobuf.LeveloneQuote.LevelOneQuote) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int instrumentId_ ;
      /**
       * <code>required int32 instrument_id = 1;</code>
       */
      public boolean hasInstrumentId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 instrument_id = 1;</code>
       */
      public int getInstrumentId() {
        return instrumentId_;
      }
      /**
       * <code>required int32 instrument_id = 1;</code>
       */
      public Builder setInstrumentId(int value) {
        bitField0_ |= 0x00000001;
        instrumentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 instrument_id = 1;</code>
       */
      public Builder clearInstrumentId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        instrumentId_ = 0;
        onChanged();
        return this;
      }

      private double bid_ ;
      /**
       * <code>required double bid = 2;</code>
       */
      public boolean hasBid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double bid = 2;</code>
       */
      public double getBid() {
        return bid_;
      }
      /**
       * <code>required double bid = 2;</code>
       */
      public Builder setBid(double value) {
        bitField0_ |= 0x00000002;
        bid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double bid = 2;</code>
       */
      public Builder clearBid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bid_ = 0D;
        onChanged();
        return this;
      }

      private double ask_ ;
      /**
       * <code>required double ask = 3;</code>
       */
      public boolean hasAsk() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double ask = 3;</code>
       */
      public double getAsk() {
        return ask_;
      }
      /**
       * <code>required double ask = 3;</code>
       */
      public Builder setAsk(double value) {
        bitField0_ |= 0x00000004;
        ask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double ask = 3;</code>
       */
      public Builder clearAsk() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ask_ = 0D;
        onChanged();
        return this;
      }

      private double last_ ;
      /**
       * <code>required double last = 4;</code>
       */
      public boolean hasLast() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double last = 4;</code>
       */
      public double getLast() {
        return last_;
      }
      /**
       * <code>required double last = 4;</code>
       */
      public Builder setLast(double value) {
        bitField0_ |= 0x00000008;
        last_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double last = 4;</code>
       */
      public Builder clearLast() {
        bitField0_ = (bitField0_ & ~0x00000008);
        last_ = 0D;
        onChanged();
        return this;
      }

      private int bidQty_ ;
      /**
       * <code>required int32 bid_qty = 5;</code>
       */
      public boolean hasBidQty() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 bid_qty = 5;</code>
       */
      public int getBidQty() {
        return bidQty_;
      }
      /**
       * <code>required int32 bid_qty = 5;</code>
       */
      public Builder setBidQty(int value) {
        bitField0_ |= 0x00000010;
        bidQty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bid_qty = 5;</code>
       */
      public Builder clearBidQty() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bidQty_ = 0;
        onChanged();
        return this;
      }

      private int askQty_ ;
      /**
       * <code>required int32 ask_qty = 6;</code>
       */
      public boolean hasAskQty() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 ask_qty = 6;</code>
       */
      public int getAskQty() {
        return askQty_;
      }
      /**
       * <code>required int32 ask_qty = 6;</code>
       */
      public Builder setAskQty(int value) {
        bitField0_ |= 0x00000020;
        askQty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ask_qty = 6;</code>
       */
      public Builder clearAskQty() {
        bitField0_ = (bitField0_ & ~0x00000020);
        askQty_ = 0;
        onChanged();
        return this;
      }

      private int lastQty_ ;
      /**
       * <code>required int32 last_qty = 7;</code>
       */
      public boolean hasLastQty() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 last_qty = 7;</code>
       */
      public int getLastQty() {
        return lastQty_;
      }
      /**
       * <code>required int32 last_qty = 7;</code>
       */
      public Builder setLastQty(int value) {
        bitField0_ |= 0x00000040;
        lastQty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 last_qty = 7;</code>
       */
      public Builder clearLastQty() {
        bitField0_ = (bitField0_ & ~0x00000040);
        lastQty_ = 0;
        onChanged();
        return this;
      }

      private long posixTime_ ;
      /**
       * <code>required int64 posix_time = 8;</code>
       */
      public boolean hasPosixTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int64 posix_time = 8;</code>
       */
      public long getPosixTime() {
        return posixTime_;
      }
      /**
       * <code>required int64 posix_time = 8;</code>
       */
      public Builder setPosixTime(long value) {
        bitField0_ |= 0x00000080;
        posixTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 posix_time = 8;</code>
       */
      public Builder clearPosixTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        posixTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:kaqt.providers.protobuf.LevelOneQuote)
    }

    static {
      defaultInstance = new LevelOneQuote(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:kaqt.providers.protobuf.LevelOneQuote)
  }

  public interface HLOCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kaqt.providers.protobuf.HLOC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 instrument_id = 1;</code>
     */
    boolean hasInstrumentId();
    /**
     * <code>required int32 instrument_id = 1;</code>
     */
    int getInstrumentId();

    /**
     * <code>required double open = 2;</code>
     */
    boolean hasOpen();
    /**
     * <code>required double open = 2;</code>
     */
    double getOpen();

    /**
     * <code>required double high = 3;</code>
     */
    boolean hasHigh();
    /**
     * <code>required double high = 3;</code>
     */
    double getHigh();

    /**
     * <code>required double low = 4;</code>
     */
    boolean hasLow();
    /**
     * <code>required double low = 4;</code>
     */
    double getLow();

    /**
     * <code>required double close = 5;</code>
     */
    boolean hasClose();
    /**
     * <code>required double close = 5;</code>
     */
    double getClose();

    /**
     * <code>required int64 posix_time = 6;</code>
     */
    boolean hasPosixTime();
    /**
     * <code>required int64 posix_time = 6;</code>
     */
    long getPosixTime();
  }
  /**
   * Protobuf type {@code kaqt.providers.protobuf.HLOC}
   */
  public static final class HLOC extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:kaqt.providers.protobuf.HLOC)
      HLOCOrBuilder {
    // Use HLOC.newBuilder() to construct.
    private HLOC(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HLOC(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HLOC defaultInstance;
    public static HLOC getDefaultInstance() {
      return defaultInstance;
    }

    public HLOC getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HLOC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              instrumentId_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              open_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              high_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              low_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              close_ = input.readDouble();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              posixTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kaqt.providers.protobuf.LeveloneQuote.internal_static_kaqt_providers_protobuf_HLOC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kaqt.providers.protobuf.LeveloneQuote.internal_static_kaqt_providers_protobuf_HLOC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kaqt.providers.protobuf.LeveloneQuote.HLOC.class, kaqt.providers.protobuf.LeveloneQuote.HLOC.Builder.class);
    }

    public static com.google.protobuf.Parser<HLOC> PARSER =
        new com.google.protobuf.AbstractParser<HLOC>() {
      public HLOC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HLOC(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HLOC> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INSTRUMENT_ID_FIELD_NUMBER = 1;
    private int instrumentId_;
    /**
     * <code>required int32 instrument_id = 1;</code>
     */
    public boolean hasInstrumentId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 instrument_id = 1;</code>
     */
    public int getInstrumentId() {
      return instrumentId_;
    }

    public static final int OPEN_FIELD_NUMBER = 2;
    private double open_;
    /**
     * <code>required double open = 2;</code>
     */
    public boolean hasOpen() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double open = 2;</code>
     */
    public double getOpen() {
      return open_;
    }

    public static final int HIGH_FIELD_NUMBER = 3;
    private double high_;
    /**
     * <code>required double high = 3;</code>
     */
    public boolean hasHigh() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double high = 3;</code>
     */
    public double getHigh() {
      return high_;
    }

    public static final int LOW_FIELD_NUMBER = 4;
    private double low_;
    /**
     * <code>required double low = 4;</code>
     */
    public boolean hasLow() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double low = 4;</code>
     */
    public double getLow() {
      return low_;
    }

    public static final int CLOSE_FIELD_NUMBER = 5;
    private double close_;
    /**
     * <code>required double close = 5;</code>
     */
    public boolean hasClose() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required double close = 5;</code>
     */
    public double getClose() {
      return close_;
    }

    public static final int POSIX_TIME_FIELD_NUMBER = 6;
    private long posixTime_;
    /**
     * <code>required int64 posix_time = 6;</code>
     */
    public boolean hasPosixTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 posix_time = 6;</code>
     */
    public long getPosixTime() {
      return posixTime_;
    }

    private void initFields() {
      instrumentId_ = 0;
      open_ = 0D;
      high_ = 0D;
      low_ = 0D;
      close_ = 0D;
      posixTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInstrumentId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHigh()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClose()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosixTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, instrumentId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, open_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, high_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, low_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, close_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, posixTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, instrumentId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, open_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, high_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, low_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, close_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, posixTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static kaqt.providers.protobuf.LeveloneQuote.HLOC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.HLOC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.HLOC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.HLOC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.HLOC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.HLOC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.HLOC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.HLOC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.HLOC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kaqt.providers.protobuf.LeveloneQuote.HLOC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(kaqt.providers.protobuf.LeveloneQuote.HLOC prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kaqt.providers.protobuf.HLOC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kaqt.providers.protobuf.HLOC)
        kaqt.providers.protobuf.LeveloneQuote.HLOCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kaqt.providers.protobuf.LeveloneQuote.internal_static_kaqt_providers_protobuf_HLOC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kaqt.providers.protobuf.LeveloneQuote.internal_static_kaqt_providers_protobuf_HLOC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kaqt.providers.protobuf.LeveloneQuote.HLOC.class, kaqt.providers.protobuf.LeveloneQuote.HLOC.Builder.class);
      }

      // Construct using kaqt.providers.protobuf.LeveloneQuote.HLOC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        instrumentId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        open_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        high_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        low_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        close_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        posixTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kaqt.providers.protobuf.LeveloneQuote.internal_static_kaqt_providers_protobuf_HLOC_descriptor;
      }

      public kaqt.providers.protobuf.LeveloneQuote.HLOC getDefaultInstanceForType() {
        return kaqt.providers.protobuf.LeveloneQuote.HLOC.getDefaultInstance();
      }

      public kaqt.providers.protobuf.LeveloneQuote.HLOC build() {
        kaqt.providers.protobuf.LeveloneQuote.HLOC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kaqt.providers.protobuf.LeveloneQuote.HLOC buildPartial() {
        kaqt.providers.protobuf.LeveloneQuote.HLOC result = new kaqt.providers.protobuf.LeveloneQuote.HLOC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.instrumentId_ = instrumentId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.open_ = open_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.high_ = high_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.low_ = low_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.close_ = close_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.posixTime_ = posixTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kaqt.providers.protobuf.LeveloneQuote.HLOC) {
          return mergeFrom((kaqt.providers.protobuf.LeveloneQuote.HLOC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kaqt.providers.protobuf.LeveloneQuote.HLOC other) {
        if (other == kaqt.providers.protobuf.LeveloneQuote.HLOC.getDefaultInstance()) return this;
        if (other.hasInstrumentId()) {
          setInstrumentId(other.getInstrumentId());
        }
        if (other.hasOpen()) {
          setOpen(other.getOpen());
        }
        if (other.hasHigh()) {
          setHigh(other.getHigh());
        }
        if (other.hasLow()) {
          setLow(other.getLow());
        }
        if (other.hasClose()) {
          setClose(other.getClose());
        }
        if (other.hasPosixTime()) {
          setPosixTime(other.getPosixTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInstrumentId()) {
          
          return false;
        }
        if (!hasOpen()) {
          
          return false;
        }
        if (!hasHigh()) {
          
          return false;
        }
        if (!hasLow()) {
          
          return false;
        }
        if (!hasClose()) {
          
          return false;
        }
        if (!hasPosixTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kaqt.providers.protobuf.LeveloneQuote.HLOC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kaqt.providers.protobuf.LeveloneQuote.HLOC) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int instrumentId_ ;
      /**
       * <code>required int32 instrument_id = 1;</code>
       */
      public boolean hasInstrumentId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 instrument_id = 1;</code>
       */
      public int getInstrumentId() {
        return instrumentId_;
      }
      /**
       * <code>required int32 instrument_id = 1;</code>
       */
      public Builder setInstrumentId(int value) {
        bitField0_ |= 0x00000001;
        instrumentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 instrument_id = 1;</code>
       */
      public Builder clearInstrumentId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        instrumentId_ = 0;
        onChanged();
        return this;
      }

      private double open_ ;
      /**
       * <code>required double open = 2;</code>
       */
      public boolean hasOpen() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double open = 2;</code>
       */
      public double getOpen() {
        return open_;
      }
      /**
       * <code>required double open = 2;</code>
       */
      public Builder setOpen(double value) {
        bitField0_ |= 0x00000002;
        open_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double open = 2;</code>
       */
      public Builder clearOpen() {
        bitField0_ = (bitField0_ & ~0x00000002);
        open_ = 0D;
        onChanged();
        return this;
      }

      private double high_ ;
      /**
       * <code>required double high = 3;</code>
       */
      public boolean hasHigh() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double high = 3;</code>
       */
      public double getHigh() {
        return high_;
      }
      /**
       * <code>required double high = 3;</code>
       */
      public Builder setHigh(double value) {
        bitField0_ |= 0x00000004;
        high_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double high = 3;</code>
       */
      public Builder clearHigh() {
        bitField0_ = (bitField0_ & ~0x00000004);
        high_ = 0D;
        onChanged();
        return this;
      }

      private double low_ ;
      /**
       * <code>required double low = 4;</code>
       */
      public boolean hasLow() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double low = 4;</code>
       */
      public double getLow() {
        return low_;
      }
      /**
       * <code>required double low = 4;</code>
       */
      public Builder setLow(double value) {
        bitField0_ |= 0x00000008;
        low_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double low = 4;</code>
       */
      public Builder clearLow() {
        bitField0_ = (bitField0_ & ~0x00000008);
        low_ = 0D;
        onChanged();
        return this;
      }

      private double close_ ;
      /**
       * <code>required double close = 5;</code>
       */
      public boolean hasClose() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required double close = 5;</code>
       */
      public double getClose() {
        return close_;
      }
      /**
       * <code>required double close = 5;</code>
       */
      public Builder setClose(double value) {
        bitField0_ |= 0x00000010;
        close_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double close = 5;</code>
       */
      public Builder clearClose() {
        bitField0_ = (bitField0_ & ~0x00000010);
        close_ = 0D;
        onChanged();
        return this;
      }

      private long posixTime_ ;
      /**
       * <code>required int64 posix_time = 6;</code>
       */
      public boolean hasPosixTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 posix_time = 6;</code>
       */
      public long getPosixTime() {
        return posixTime_;
      }
      /**
       * <code>required int64 posix_time = 6;</code>
       */
      public Builder setPosixTime(long value) {
        bitField0_ |= 0x00000020;
        posixTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 posix_time = 6;</code>
       */
      public Builder clearPosixTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        posixTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:kaqt.providers.protobuf.HLOC)
    }

    static {
      defaultInstance = new HLOC(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:kaqt.providers.protobuf.HLOC)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kaqt_providers_protobuf_LevelOneQuote_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kaqt_providers_protobuf_LevelOneQuote_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kaqt_providers_protobuf_HLOC_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kaqt_providers_protobuf_HLOC_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024levelone_quote.proto\022\027kaqt.providers.p" +
      "rotobuf\"\226\001\n\rLevelOneQuote\022\025\n\rinstrument_" +
      "id\030\001 \002(\005\022\013\n\003bid\030\002 \002(\001\022\013\n\003ask\030\003 \002(\001\022\014\n\004la" +
      "st\030\004 \002(\001\022\017\n\007bid_qty\030\005 \002(\005\022\017\n\007ask_qty\030\006 \002" +
      "(\005\022\020\n\010last_qty\030\007 \002(\005\022\022\n\nposix_time\030\010 \002(\003" +
      "\"i\n\004HLOC\022\025\n\rinstrument_id\030\001 \002(\005\022\014\n\004open\030" +
      "\002 \002(\001\022\014\n\004high\030\003 \002(\001\022\013\n\003low\030\004 \002(\001\022\r\n\005clos" +
      "e\030\005 \002(\001\022\022\n\nposix_time\030\006 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kaqt_providers_protobuf_LevelOneQuote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kaqt_providers_protobuf_LevelOneQuote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_kaqt_providers_protobuf_LevelOneQuote_descriptor,
        new java.lang.String[] { "InstrumentId", "Bid", "Ask", "Last", "BidQty", "AskQty", "LastQty", "PosixTime", });
    internal_static_kaqt_providers_protobuf_HLOC_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kaqt_providers_protobuf_HLOC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_kaqt_providers_protobuf_HLOC_descriptor,
        new java.lang.String[] { "InstrumentId", "Open", "High", "Low", "Close", "PosixTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
